django:
  debug: true
  secret_key: "change-me-in-production"
  allowed_hosts: 
    - "*"
  database_type: "mongodb"

mongo:
  url: "mongodb://mongo:27017" # Service name 'mongo'
  db_name: "openanomaly"

redis:
  url: "redis://redis:6379/0" # Service name 'redis'

prometheus:
  url: "http://victoriametrics:8428"
  # write_url: "http://victoriametrics:8428/api/v1/write"

pipelines_file: "pipelines.yaml"
config_store_type: "yaml"
