services:
  mongo:
    image: mongo:latest
    container_name: openanomaly-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  minio:
    image: minio/minio
    container_name: openanomaly-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.93.4
    container_name: openanomaly-vm
    ports:
      - "8428:8428"
    volumes:
      - vm-data:/victoria-metrics-data
    command:
      - "-storageDataPath=/victoria-metrics-data"
      - "-retentionPeriod=1y"

  redis:
    image: redis:alpine
    container_name: openanomaly-redis
    ports:
      - "6379:6379"

volumes:
  mongo-data:
  minio-data:
  vm-data:
