[project]
name = "openanomaly"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "celery>=5.6.1",
    "fastapi>=0.128.0",
    "nixtla>=0.7.2",
    "pymongo>=4.15.5",
    "streamlit>=1.52.2",
    "uvicorn>=0.40.0",
    "opentelemetry-exporter-prometheus-remote-write>=0.43b0",
    "opentelemetry-sdk>=1.22.0",
    "opentelemetry-api>=1.22.0",
]
