{{- if .Values.api.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openanomaly.fullname" . }}-api
  labels:
    {{- include "openanomaly.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ .Values.api.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "openanomaly.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}
