apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openanomaly.fullname" . }}-secret
  labels:
    {{- include "openanomaly.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
